version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: crypto-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_DATABASE: crypto
    networks:
      - crypto-network

  web:
    build:
      context: .
      target: ${BUILD_TARGET:-development}
    container_name: crypto-web
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/crypto
    networks:
      - crypto-network

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
      target: ${BUILD_TARGET:-development}
    container_name: crypto-scraper
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/crypto
    networks:
      - crypto-network

volumes:
  mongo-data:
  mongo-config:

networks:
  crypto-network:
    driver: bridge