version: '3.8'

services:
  mongodb:
    restart: unless-stopped

  web:
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev"]

  scraper:
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev:scraper"]