version: '3.8'

services:
  mongodb:
    restart: unless-stopped
  web:
    restart: unless-stopped
    # Re-expose port for direct access during development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev"]
  
  nginx:
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  scraper:
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev:scraper"]