version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: crypto-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_DATABASE: crypto
    networks:
      - crypto-network

  web:
    build:
      context: .
      target: ${BUILD_TARGET:-development}
    container_name: crypto-web
    # Remove external port mapping - only accessible through nginx
    expose:
      - "3000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/crypto
    networks:
      - crypto-network

  nginx:
    build:
      context: ./nginx
    container_name: crypto-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    networks:
      - crypto-network

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
      target: ${BUILD_TARGET:-development}
    container_name: crypto-scraper
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/crypto
    networks:
      - crypto-network

volumes:
  mongo-data:
  mongo-config:
  certbot-conf:
  certbot-www:

networks:
  crypto-network:
    driver: bridge