version: '3.8'

services:
  mongodb:
    restart: always
    ports:
      - "127.0.0.1:27017:27017"  # Bind only to localhost

  web:
    restart: always
    environment:
      NODE_ENV: production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  scraper:
    restart: always
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M